# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

FACEBOOK_APP_ID: "id here"
FACEBOOK_APP_SECRET_ID: "id secret here"
GMAIL_USERNAME: "username here"
GMAIL_PASS: "pass here"
AWS_ACCESS_KEY_ID: "sadkjaskjdhaksjdhajsh"
AWS_SECRET_KEY: "asldkj1lkjwld1lkasldk"
S3_BUCKET: "bucket name here"
DEVISE_SECRET_KEY: "askdhaskjdhasd"